CREATE TABLE EMPLOYEE(
Fname VARCHAR(20),
Minit CHAR,
Lname VARCHAR(20),
SSN INT,
Bdate DATE,
Address VARCHAR(50),
Sex CHAR,
Salary INT,
Super_ssn INT,
Dno INT,
PRIMARY KEY(SSN)
)

ALTER TABLE EMPLOYEE ADD FOREIGN KEY(Super_ssn) REFERENCES EMPLOYEE(SSN)

ALTER TABLE EMPLOYEE ADD FOREIGN KEY(Dno) REFERENCES DEPARTMENT(Dnumber)

DESC EMPLOYEE



CREATE TABLE DEPARTMENT(
Dname VARCHAR(20),
Dnumber INT NOT NULL,
Mgr_ssn INT,
Mgr_start_date DATE,
PRIMARY KEY(Dnumber)
)

ALTER TABLE DEPARTMENT ADD FOREIGN KEY(Mgr_ssn) REFERENCES EMPLOYEE(Ssn)


DESC DEPARTMENT


CREATE TABLE DEPT_LOCATIONS(
Dnumber INT NOT NULL,
Dlocation VARCHAR(20),
PRIMARY KEY(Dnumber, Dlocation)
)

ALTER TABLE DEPT_LOCATIONS ADD FOREIGN KEY(Dnumber) REFERENCES Department(Dnumber)

DESC DEPT_LOCATIONS


CREATE TABLE PROJECT(
Pname VARCHAR(20),
Pnumber INT,
Plocation VARCHAR(20),
Dnum INT,
PRIMARY KEY(Pnumber)
)

ALTER TABLE PROJECT ADD FOREIGN KEY(Dnum) REFERENCES Department(Dnumber)

DESC PROJECT

CREATE TABLE WORKS_ON(
Essn INT,
Pno INT,
Hours FLOAT,
PRIMARY KEY(Essn, Pno)
)

ALTER TABLE WORKS_ON ADD FOREIGN KEY(Essn) REFERENCES EMPLOYEE(SSN)

ALTER TABLE WORKS_ON ADD FOREIGN KEY(Pno) REFERENCES PROJECT(Pnumber)

DESC WORKS_ON


CREATE TABLE DEPENDENT(
Essn INT,
Dependent_name VARCHAR(20),
Sex CHAR,
Bdate DATE,
Relationship VARCHAR(20),
PRIMARY KEY(Essn, Dependent_name)
)

ALTER TABLE DEPENDENT ADD FOREIGN KEY(Essn) REFERENCES EMPLOYEE(SSN)

DESC DEPENDENT
