CREATE OR REPLACE PACKAGE DEMO AS
    PROCEDURE insertRecord;
END;

CREATE OR REPLACE PACKAGE BODY DEMO AS
    PROCEDURE insertRecord AS
    BEGIN
        INSERT INTO STUDENT_COURSE VALUES (40, 60);
    END;
END DEMO;


BEGIN
DEMO.insertRecord;
END;