DECLARE

E_FNAME EMPLOYEE.FNAME%TYPE ;
E_MNAME EMPLOYEE.MINIT%TYPE ;
E_LNAME EMPLOYEE.LNAME%TYPE ;
E_SEX EMPLOYEE.SEX%TYPE;
E_ADDRESS EMPLOYEE.ADDRESS%TYPE;
E_SALARY EMPLOYEE.SALARY%TYPE;
E_SSN EMPLOYEE.SSN%TYPE;
E_BDATE EMPLOYEE.BDATE%TYPE;
E_DNO EMPLOYEE.DNO%TYPE;
E_SUPERSSN EMPLOYEE.SUPER_SSN%TYPE;

CURSOR E_EMPLOYEE IS SELECT FNAME,MINIT,LNAME,SEX,ADDRESS,SALARY,SSN,BDATE,DNO,SUPER_SSN FROM EMPLOYEE;

BEGIN
OPEN E_EMPLOYEE;

LOOP
FETCH E_EMPLOYEE INTO

E_FNAME, E_MNAME, E_LNAME, E_SEX, E_ADDRESS, E_SALARY, E_SSN, E_BDATE, E_DNO, E_SUPERSSN;

EXIT WHEN E_EMPLOYEE%NOTFOUND;

DBMS_OUTPUT.PUT_LINE(E_FNAME || CHR(9) || E_MNAME || CHR(9) || E_LNAME || CHR(9) || E_SEX || CHR(9) || E_ADDRESS || CHR(19) || E_SALARY || CHR(9) || E_SSN || CHR(9) || E_BDATE || CHR(9) || E_DNO || CHR(9)|| E_SUPERSSN);

END LOOP;
CLOSE E_EMPLOYEE;
END;
/