CREATE TABLE CLASS(ID INT PRIMARY KEY, NAME VARCHAR(20));

INSERT INTO CLASS VALUES(1, 'Abhi');
INSERT INTO CLASS VALUES(2, 'Adam');
INSERT INTO CLASS VALUES(4, 'Alex');
SELECT * FROM CLASS

INSERT INTO CLASS VALUES(5, 'Rahul');
COMMIT;
UPDATE CLASS SET NAME='Abhijit' WHERE ID=5;
SAVEPOINT A;
INSERT INTO CLASS VALUES(6, 'Chris');
SAVEPOINT B;
INSERT INTO CLASS VALUES(7, 'Bravo');
SAVEPOINT C;
SELECT * FROM CLASS

ROLLBACK TO A;
SELECT * FROM CLASS
